### ISSUE TITLE
Version 0.5.3 - Verify secp128r1 signature

### ISSUE THREAD

**Issue by andrea-spotsoftware** [cryptocoinjs/ecdsa#16]
Hello there,
I'm struggling with this problem and I can't find a solution.

I'm working with version 0.5.3, because i need secp128r1 curve.

I have a 32 byte public key in buffer format.
I have a 7 byte buffer, let's call it plain-text.
I have a 32 byte signature of the plain-text, using the secp128r1 encryption algorithm.

I'm not able to verify this signature, there is an exception thrown on the verify.

The code: http://pastebin.com/Eas4nByG

The exception is thrown with this message:
{ [AssertionError: Invalid signature.]                                                                                                      
  name: 'AssertionError',                                                                                                                   
  actual: undefined,                                                                                                                        
  expected: true,                                                                                                                           
  operator: '==',                                                                                                                           
  message: 'Invalid signature.' }  

Am I missing something?

**Comment by jprichardson** [comment]
Closing. Unwilling to support `secp128r1` for the time being.
