### ISSUE TITLE
RFC 6979 compliance for out of bounds k

### ISSUE THREAD

**Issue by jprichardson** [cryptocoinjs/ecdsa#20]
See:
- https://github.com/bitcoinjs/bitcoinjs-lib/pull/337
- https://github.com/bitcoinjs/bitcoinjs-lib/pull/336
- https://github.com/bitpay/bitcore/pull/884

**Comment by bip32JP** [comment]
Current implementation throws an error for both out of bounds k and for r == 0 or s == 0.

The failure loop is not implemented at all.

**Comment by jprichardson** [comment]
https://github.com/cryptocoinjs/ecdsa/tree/0.7.0
