### ISSUE TITLE
Can ecurve/ecdsa use bitcoin's wallet public key to encrypt a message?

### ISSUE THREAD

**Issue by Livshitz** [cryptocoinjs/ecdsa#26]
I'd like to perform asymmetric encryption using the public key (derived from wallet address) and decrypt by private key.

I assume 'bitcoinjs-message' uses ecurve/ecdsa internally to hash and sign a message, and I know ECDSA in general is capable of asymmetric encryption, but can't find example or MB it's not even implemented.

**Comment by fanatid** [comment]
Duplicate issue. Answer here: https://github.com/cryptocoinjs/ecurve/issues/35#issuecomment-376010108
