### ISSUE TITLE
Error: Expected property "1" of type BigInteger, got Buffer

### ISSUE THREAD

**Issue by liu-yi** [cryptocoinjs/ecdsa#27]
I just run the example in http://cryptocoinjs.com/modules/crypto/ecdsa/ 
I do not change any code from the example, however it seems that there are some problems...

Could you please help me?

> c:\Users\45288\GraduationProject\ringSign\node_modules\typeforce\index.js:159
>           throw tfSubError(e, i)
>           ^
> Error: Expected property "1" of type BigInteger, got Buffer
>     at tfSubError (c:\Users\45288\GraduationProject\ringSign\node_modules\typeforce\errors.js:93:9)
>     at c:\Users\45288\GraduationProject\ringSign\node_modules\typeforce\index.js:159:17
>     at Array.every (<anonymous>)
>     at _tuple (c:\Users\45288\GraduationProject\ringSign\node_modules\typeforce\index.js:155:20)
>     at typeforce (c:\Users\45288\GraduationProject\ringSign\node_modules\typeforce\index.js:196:9)
>     at Object.sign (c:\Users\45288\GraduationProject\ringSign\node_modules\ecdsa\lib\ecdsa.js:81:3)
>     at Object.<anonymous> (c:\Users\45288\GraduationProject\ringSign\ringSign.js:12:23)
>     at Module._compile (module.js:646:14)
>     at Object.Module._extensions..js (module.js:660:10)
>     at Module.load (module.js:561:32)
> TfPropertyTypeError

**Comment by liu-yi** [comment]
The code is 
```
var crypto = require('crypto') //Node.js or Browserify (browser)

var ecdsa = require('ecdsa')
var sr = require('secure-random') //npm install --save secure-random@1.x
var CoinKey = require('coinkey') //npm install --save coinkey@0.1.0

var privateKey = sr.randomBuffer(32)
var ck = new CoinKey(privateKey, true) // true => compressed public key / addresses

var msg = new Buffer("hello world!", 'utf8')
var shaMsg = crypto.createHash('sha256').update(msg).digest()
var signature = ecdsa.sign(shaMsg, ck.privateKey)
var isValid = ecdsa.verify(shaMsg, signature, ck.publicKey)
console.log(isValid) //true
```

**Comment by taurus-kuchain** [comment]
I got the same problem

**Comment by junderw** [comment]
Please see the README here on Github.

# Deprecated

Use [secp256k1](https://github.com/cryptocoinjs/secp256k1-node) or [elliptic](https://github.com/indutny/elliptic) if you need other curves.
